### PR TITLE
Better usability for url paths

### LINKED ISSUE #50: Better paths for better usability
**Describe the problem you are experiencing**
When currently using the page, the home page is located at /pages/main/home. Same goes for pages like aboutCYB and so on.

**Describe the solution you'd like**
I believe it would be better to have the homepage located at / and profile at /profile and so on

**Describe alternatives you've considered**
Next uses the file structure of the project to generate the url paths, so to make the paths more usable, I see two options:
 1. Restructure the entrire project to better take advantage of nexts auto path generating
 2. Add parenthesis to folders like pages and main to make next ignore these directories when generating paths

**Additional context**
I've tested the latter option, and have gotten the page to work like i imagined using this method.
Only problem is that all links to the page need to be changed to not include the /pages/main part. This includes links i believe are stored in the CMS

### PR DESCRIPTION
**Pull request by Sebbben**
resolves #50 
Renaming the pages and main folders to "(pages)" and "(main)" next will now ignore them as a part of the url structure.
This effectively  removes the /pages/main part of all urls
All links accept the links stored in CMS are allso updated

### CODE REVIEW

**Comment by Sebbben** [comment]
Think it might be smart to merge this as fast as possible to make sure there is the least amount of merge friction.

**Review by EricSvebakk — CHANGES_REQUESTED** [review]
This is a good idea, well done for remembering to update the yaml scripts and readme. 

However, there are some issues. You did not update the path for the Home item in the Navitems list, which is found in the base layout file. Without this change, the home page will not be highlighted when users navigate to the page.

The path should be set to the empty string to reflect the changes in the url path. The pull-request can be accepted once this has been fixed.

The redirect to the /rentingEscape page is also broken, but this must be fixed from the CMS so I will handle this after the pull-request is accepted.

image
image
image

**Review by EricSvebakk — APPROVED** [review]
It looks like you have been consistent in updating all the references to the url-path in the project. Good job.

**Comment by EricSvebakk** [comment]
Dang. noticed an issue after merging to the Development-branch. It seems that your pull-request was based on an outdated version of the Main branch which did not include the code for route /board, which is a boardmember-only page. The merge will be reverted, and this will have to be updated.

**Comment by yrjarv** [comment]
I just noticed that uio.no's information page for [Ole-Johan Dahls hus (GA06)](https://www.uio.no/om/finn-fram/omrader/gaustad/ga06/) links to the home page in the old structure. First of all, EA should probably be informed so they can change the link on the webpage. But of course, uio.no probably isn't the only site linking to the old home page. So perhaps there should be a manual redirect in place from cyb.no/pages/main/home to cyb.no/home?

**Comment by EricSvebakk** [comment]
The pull-request has been accepted into main. The missing route was experimental and not necessary to include for the operation of the website. This will be handled more carefully next time.

Regaring the url on uio's page, the url seems to still work after the changes have been made to main. Worst-case, if the link stops working for some reason, then the link-text also includes the correct url: cyb.no.

**Pull request merged**
