### PR TITLE
Fix prisma request for membership creation

### LINKED ISSUE #55: Comments not appearing on membership page
When creating a new member in /pages/main/volunteering/membership, the comment doesn't show up in the table

**To Reproduce**
Go to http://localhost:3005/pages/main/volunteering/membership, and enter a random name and a comment. Press "Add new member". The member will then show up in the table on the right, but the comment you inputted will not. This issue seems to be on cyb.no too, but I do not want to send test data to the prod database.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by yrjarv**
Resolves #55

### CODE REVIEW

**Comment by Sebbben** [comment]
This change does not fix the issue. The database has the field comments, not comment. To fix this you can instead change [this line](https://github.com/cybernetisk/internsystem-v2/blob/ebe4c43df04a4147d25a195d90ffa2ebf8365bd4/app/(pages)/(main)/volunteering/membership/page.js#L48) to comments to get the comments value

**Comment by yrjarv** [comment]
It does not work in the dev database, however it should work in prod according to https://github.com/cybernetisk/internsystem-v2/issues/55#issuecomment-2377057128
If it is OK for @EricSvebakk I can change the field name in the dev DB, but because I do not have access to the prod DB (as I shouldn' have) I cannot verify if the same change has been made there.

**Comment by Sebbben** [comment]
Ahh my b, nvm then

**Review by EricSvebakk — APPROVED** [review]
Looks good. This is the agreed upon change.

**Comment by EricSvebakk** [comment]
Due to a merge conflict, I will handle this when I am back from vacation.

**Pull request merged**
